apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - name: my-app-port
      port: 8080
      targetPort: 3000
    # - name: postgres-port
    #   port: 8090
    #   targetPort: 5432